import type { CareerActivityType, DailyRoadmapActionType } from "@/generated/prisma/client";

const MEANINGFUL_BY_TYPE: Record<DailyRoadmapActionType, boolean> = {
  JOB_REVIEW: false,
  JOB_PREPARE: true,
  JOB_APPLY: true,
  APPLICATION_FOLLOW_UP: true,
  APPLICATION_NEXT_STEP: true,
  INTERVIEW_PREP: true,
  ASSESSMENT_PREP: true,
  RESUME_REVIEW: true,
  COMMUNICATION_REVIEW: true,
  LINKEDIN_POST_REVIEW: true,
  LINKEDIN_PUBLISH: true,
  LINKEDIN_ANALYTICS_REVIEW: false,
  LINKEDIN_RECONNECT: false,
  SKILL_DEVELOPMENT: true,
  EVIDENCE_BUILDING: true,
  PROFILE_IMPROVEMENT: true,
  WEEKLY_PREP: false,
  CUSTOM_CAREER_ACTION: true,
};

const ACTIVITY_FOR_TYPE: Partial<Record<DailyRoadmapActionType, CareerActivityType>> = {
  JOB_PREPARE: "ROADMAP_ACTION_COMPLETED",
  JOB_APPLY: "ROADMAP_ACTION_COMPLETED",
  APPLICATION_FOLLOW_UP: "ROADMAP_ACTION_COMPLETED",
  APPLICATION_NEXT_STEP: "ROADMAP_ACTION_COMPLETED",
  INTERVIEW_PREP: "INTERVIEW_PREP_COMPLETED",
  ASSESSMENT_PREP: "ASSESSMENT_PREP_COMPLETED",
  RESUME_REVIEW: "ROADMAP_ACTION_COMPLETED",
  COMMUNICATION_REVIEW: "ROADMAP_ACTION_COMPLETED",
  LINKEDIN_POST_REVIEW: "ROADMAP_ACTION_COMPLETED",
  LINKEDIN_PUBLISH: "ROADMAP_ACTION_COMPLETED",
  SKILL_DEVELOPMENT: "SKILL_ACTION_COMPLETED",
  EVIDENCE_BUILDING: "EVIDENCE_ACTION_COMPLETED",
  PROFILE_IMPROVEMENT: "ROADMAP_ACTION_COMPLETED",
  CUSTOM_CAREER_ACTION: "ROADMAP_ACTION_COMPLETED",
};

export function isMeaningfulActionType(type: DailyRoadmapActionType): boolean {
  return MEANINGFUL_BY_TYPE[type];
}

export function activityTypeForRoadmapAction(
  type: DailyRoadmapActionType,
): CareerActivityType | null {
  if (!isMeaningfulActionType(type)) return null;
  return ACTIVITY_FOR_TYPE[type] ?? "ROADMAP_ACTION_COMPLETED";
}
